version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok # ✅ บังคับให้ PostgreSQL ใช้ Timezone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
 
    depends_on:
      - postgres
    command: [ "npm", "run", "start:prod" ] # รันคำสั่งเพื่อเริ่มแอปในโหมด production

volumes:
  postgres_data:


